name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set PYTHONPATH
        run:  echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-timeout
          
      - name: Run tests
        run: pytest --timeout=10

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image for EC2 Ubuntu 24.04 (x86_64)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t olegbulka/public-repo:devlaunch-api-1.0-amd64 \
            --push .

